4DNucleome/PartSeg

launcher.spec, package/PartSegCore/__init__.py, package/PartSegCore/analysis/calculation_plan.py, package/PartSegCore/analysis/load_functions.py, package/PartSegCore/analysis/measurement_calculation.py, package/PartSegCore/analysis/save_functions.py, package/PartSegCore/mask/io_functions.py, package/PartSegCore/mask_create.py, package/PartSegCore/register.py
=> try fix lgtm cyclic code warning

package/PartSegCore/distance_in_structure/euclidean_cython.pyx, package/PartSegCore/distance_in_structure/find_split.py, package/PartSegCore/distance_in_structure/fuzzy_distance.pyx, package/PartSegCore/distance_in_structure/sprawl_utils.pyx, package/tests/test_segmentation.py
fix error with over five components in sprawl (introduced by fix reducing memory usage)
=> Sprawl over 5 elem fix

azure-pipelines.yml, package/PartSeg/common_backend/base_argparser.py, package/PartSeg/common_backend/segmentation_thread.py, package/PartSeg/common_gui/algorithms_description.py, package/PartSeg/common_gui/error_report.py, package/PartSeg/segmentation_mask/batch_proceed.py, package/PartSegCore/algorithm_describe_base.py, package/PartSegCore/analysis/analysis_utils.py, package/PartSegCore/analysis/batch_processing/batch_backend.py, package/PartSegCore/analysis/batch_processing/parallel_backend.py, package/PartSegCore/analysis/calculate_pipeline.py, package/PartSegCore/analysis/calculation_plan.py, package/PartSegCore/mask_create.py, package/PartSegCore/segmentation/algorithm_base.py, package/PartSegImage/image.py, package/tests/test_qt_part/test_sentry.py, requirements/minimal-req.txt, requirements/requirements_pyinstaller.in, requirements/requirements_pyinstaller.txt, setup.py
=> Beter reporing system

azure-pipelines.yml, package/PartSeg/__init__.py, package/PartSeg/common_backend/base_argparser.py, package/PartSeg/common_backend/except_hook.py, package/PartSeg/common_backend/segmentation_thread.py, package/PartSeg/common_gui/algorithms_description.py, package/PartSeg/common_gui/error_report.py, package/PartSeg/segmentation_analysis/batch_window.py, package/PartSeg/segmentation_mask/batch_proceed.py, package/PartSegCore/algorithm_describe_base.py, package/PartSegCore/analysis/analysis_utils.py, package/PartSegCore/analysis/batch_processing/batch_backend.py, package/PartSegCore/analysis/batch_processing/parallel_backend.py, package/PartSegCore/analysis/calculate_pipeline.py, package/PartSegCore/analysis/calculation_plan.py, package/PartSegCore/mask_create.py, package/PartSegCore/segmentation/algorithm_base.py, package/PartSegImage/image.py, package/tests/test_qt_part/test_sentry.py, requirements/minimal-req.txt, requirements/requirements_pyinstaller.in, requirements/requirements_pyinstaller.txt, setup.py
_again because of code linter errors_
=> Better reporting system #2

package/PartSeg/_roi_analysis/batch_window.py, package/PartSeg/_roi_analysis/prepare_plan_widget.py, package/PartSeg/common_gui/select_multiple_files.py, package/tests/test_qt_part/test_common_gui.py
Allow to load files using drag'n'drop list of paths on batch window. Paths could be relative to selected directory.
=> Drag'n'Dropr file list load

azure-pipelines.yml, package/PartSeg/_roi_analysis/batch_window.py, package/PartSeg/common_backend/base_settings.py, package/PartSeg/common_gui/main_window.py, package/PartSeg/common_gui/select_multiple_files.py, package/tests/test_qt_part/test_common_gui.py, package/tests/test_qt_part/test_main_windows.py
Allow to load to main UI file from batch list
=> Preview image from batch

package/PartSegCore/analysis/batch_processing/batch_backend.py, package/PartSegCore/analysis/batch_processing/parallel_backend.py, package/tests/test_PartSegCore/test_analysis_batch.py
Add information about failed files in batch result excel file.
=> report failed in batch

package/PartSeg/common_backend/base_settings.py, package/PartSeg/common_gui/channel_control.py, package/PartSeg/common_gui/main_window.py, package/PartSegCore/project_info.py, setup.cfg
=> Fix colormap save problem and minor things connected with open files history

package/PartSeg/_roi_analysis/main_window.py, package/PartSeg/_roi_mask/main_window.py, package/PartSeg/common_backend/base_settings.py, package/PartSeg/common_gui/channel_control.py, package/PartSeg/common_gui/main_window.py, package/PartSeg/common_gui/multiple_file_widget.py
=> History of last opened files

package/PartSeg/common_gui/algorithms_description.py, package/PartSeg/plugins/old_partseg/__init__.py, package/PartSegCore/algorithm_describe_base.py, package/PartSegCore/class_generator.py, package/PartSegCore/segmentation/algorithm_base.py, package/PartSegCore/segmentation/restartable_segmentation_algorithms.py, package/PartSegCore/segmentation/segmentation_algorithm.py, package/PartSegCore/segmentation/threshold.py, package/PartSegCore/segmentation/watershed.py, package/tests/test_PartSegCore/segmentation/test_segmentation_algorithm.py, package/tests/test_PartSegCore/segmentation/test_threshold.py
Add test for segmentation algorithm. 
Fix found bugs.
=> Add tests for segmentaion

package/PartSegCore/analysis/batch_processing/batch_backend.py, package/PartSegCore/analysis/batch_processing/parallel_backend.py, package/PartSegCore/segmentation/border_smoothing.py, package/tests/test_PartSegCore/segmentation/test_threshold.py, package/tests/test_PartSegCore/test_analysis_batch.py, setup.cfg, tox-minimal.ini, tox.ini
fixes to work with SimpleITK 2.*
=> Fixes for SimpleITK 2.*

.github/workflows/tests.yml, azure-pipelines.yml, changelog.md, package/PartSeg/_roi_mask/main_window.py, package/PartSeg/_roi_mask/stack_settings.py, package/PartSegCore/segmentation/algorithm_base.py
=> Fix additional_layers assign bug

package/PartSegCore/analysis/calculate_pipeline.py, package/PartSegCore/mask_create.py, package/tests/test_PartSegCore/test_pipeline.py, package/tests/test_PartSegCore/test_segmentation.py
fix time iteration with an old mask
fix PARTSEG-8N
=> Fix pipeline execute

changelog.md, package/PartSeg/common_backend/base_settings.py, package/PartSeg/common_gui/algorithms_description.py, package/PartSeg/plugins/modeling_save/save_modeling_data.py, package/PartSegCore/algorithm_describe_base.py, package/PartSegCore/analysis/save_functions.py, package/PartSegCore/mask_partition_utils.py, package/PartSegCore/register.py, package/PartSegCore/segmentation/noise_filtering.py, package/PartSegCore/segmentation/restartable_segmentation_algorithms.py, package/PartSegCore/segmentation/segmentation_algorithm.py, package/PartSegCore/segmentation/threshold.py, package/PartSegCore/segmentation/watershed.py
This PR allows adding used defined widgets for parameters of the algorithm.
=> Allow custom input widget for algorithm parameters

.github/workflows/tests.yml, package/PartSeg/launcher_main.py, package/tests/test_PartSeg/test_sentry.py, tox.ini
I have hope that this PR will fix most of the random test failure.
=> Fix part of non code related fails in test 

package/PartSeg/common_gui/main_window.py
This PR introduces a small fix for the history of the last opened files.
=> Update order of recent opened files when use last files menu

.pre-commit-config.yaml, azure-pipelines.yml, requirements/requirements_dev.txt, requirements/requirements_pyinstaller.in, requirements/requirements_pyinstaller.txt, setup.cfg, tox.ini
=> Move testing notebook and docs to tox

changelog.md, package/PartSeg/launcher_main.py, setup.cfg
=> fixes for napari 0.4.6

.github/workflows/tests.yml, requirements/requirements_pyinstaller.in, requirements/requirements_pyinstaller.txt, tox.ini
Bump bundle requirements before 0.13.0 release
=> Bump requirements

package/PartSeg/common_gui/napari_image_view.py, package/PartSeg/common_gui/stack_image_view.py
=> Small fix to prevent failture on mailformated colormaps

changelog.md, package/PartSegCore/algorithm_describe_base.py
=> Fix error on outdated profile show

package/PartSeg/common_gui/napari_image_view.py
this PR fix deprecation warnings
=> replace QtNDisplayButton with QtStateButton

package/PartSegCore/segmentation/threshold.py, package/PartSegCore/segmentation/watershed.py, package/tests/test_PartSegCore/segmentation/test_threshold.py
=> Proper propagate errors from algorthms as warnings, not error reports

package/PartSeg/_roi_analysis/main_window.py, package/PartSeg/_roi_mask/stack_settings.py, package/PartSeg/common_backend/base_settings.py, package/PartSeg/common_backend/segmentation_thread.py, package/PartSeg/common_gui/algorithms_description.py, package/PartSegCore/analysis/calculate_pipeline.py, package/PartSegCore/segmentation/__init__.py, package/PartSegCore/segmentation/algorithm_base.py, package/PartSegCore/segmentation/restartable_segmentation_algorithms.py, package/PartSegCore/segmentation/segmentation_algorithm.py, package/tests/test_PartSeg/test_settings.py, package/tests/test_PartSegCore/segmentation/test_algorithm_base.py, package/tests/test_PartSegCore/segmentation/test_segmentation_algorithm.py, package/tests/test_PartSegCore/test_io.py
=> Fix bug with change image during ROI calculation

changelog.md, package/PartSeg/_roi_mask/stack_settings.py, package/PartSegCore/algorithm_describe_base.py, package/tests/test_PartSeg/test_settings.py
=> Fix missing components selector

package/PartSeg/_roi_mask/image_view.py, package/PartSeg/common_gui/algorithms_description.py, package/PartSeg/common_gui/napari_image_view.py, package/PartSegCore/analysis/save_functions.py, package/PartSegCore/mask/io_functions.py, requirements/requirements_pyinstaller.in, requirements/requirements_test.txt, setup.cfg, tox.ini
fix deprecation for a new naparii version and few other fixes
=> Napari deprecation

package/PartSeg/_roi_analysis/advanced_window.py, package/PartSegCore/analysis/batch_processing/batch_backend.py
Remove possibility to add twice same ratio to measurements (related to PARTSEG-B4)
Get earlier bug information by moving some checks higher in a call stack.
=> Check if len of data is equal to number of columns

package/PartSeg/_roi_analysis/main_window.py, package/PartSeg/_roi_analysis/partseg_settings.py, package/PartSeg/_roi_mask/main_window.py
=> Fix bug in previous mask operation

Readme.md, package/PartSeg/_roi_analysis/main_window.py, package/PartSeg/common_gui/napari_image_view.py, tox.ini
=> fix pipeline result consume

package/PartSeg/_roi_mask/simple_measurements.py, package/PartSeg/common_gui/main_window.py, package/PartSeg/common_gui/napari_image_view.py, package/PartSeg/plugins/napari/measurement_widget.py, package/PartSegCore/analysis/measurement_base.py, package/PartSegCore/analysis/measurement_calculation.py, package/PartSegCore/mask_create.py, package/PartSegCore/napari_plugins/save_mask_roi.py, package/PartSegImage/image.py, package/tests/test_PartSegCore/test_analysis_batch.py, package/tests/test_PartSegCore/test_base.py, package/tests/test_PartSegCore/test_class_generator.py, package/tests/test_PartSegCore/test_image_adjustment.py, package/tests/test_PartSegCore/test_io.py, package/tests/test_PartSegCore/test_json_hooks.py, package/tests/test_PartSegCore/test_mask_create.py, package/tests/test_PartSegCore/test_mask_partition.py, package/tests/test_PartSegCore/test_measurements.py, package/tests/test_PartSegCore/test_mso.py, package/tests/test_PartSegCore/test_napari_plugins.py, package/tests/test_PartSegCore/test_pipeline.py, package/tests/test_PartSegCore/test_segmentation.py, package/tests/test_PartSegCore/test_segmentation_proceses.py, package/tests/test_PartSegCore/test_smooth.py, setup.cfg
This PR adds a simple measurement widget as a napari plugin.
=> Add measurement widget for napari

launcher.spec, package/PartSeg/launcher_main.py
fix missed freetype on test procedure
=> Check freetype import on test procedure

.github/workflows/test_prereleases.yml, .github/workflows/tests.yml, package/tests/conftest.py, setup.cfg, tox.ini
this PR change manual xvfb call to use action
=> Change manual xvfb run to action

package/PartSeg/_roi_analysis/batch_window.py, package/PartSeg/_roi_analysis/main_window.py, package/PartSeg/_roi_mask/main_window.py, package/PartSeg/common_gui/custom_load_dialog.py, package/PartSeg/common_gui/main_window.py, package/PartSeg/common_gui/qt_console.py, package/PartSegCore/analysis/batch_processing/batch_backend.py, package/PartSegCore/analysis/batch_processing/parallel_backend.py, package/PartSegCore/analysis/calculation_plan.py, package/PartSegCore/analysis/measurement_calculation.py, package/PartSegCore/roi_info.py, package/tests/test_PartSegCore/test_measurements.py
=> Add remove/cancel task in batch procesing

Readme.md, package/PartSeg/_roi_analysis/prepare_plan_widget.py, package/PartSeg/common_backend/base_settings.py, package/PartSeg/common_backend/image_read_thread.py, package/PartSeg/common_backend/progress_thread.py, package/PartSeg/common_backend/segmentation_thread.py, package/PartSeg/common_gui/algorithms_description.py, package/PartSeg/common_gui/napari_image_view.py, package/PartSeg/custom_application/application.py, package/PartSegCore/analysis/batch_processing/batch_backend.py, package/PartSegCore/analysis/batch_processing/parallel_backend.py, package/PartSegCore/analysis/measurement_base.py, package/PartSegCore/analysis/measurement_calculation.py, package/PartSegCore/class_generator.py, package/PartSegCore/convex_fill.py, package/tests/test_PartSeg/test_channel_control.py
=> Fix deepsource warnings

package/PartSeg/_roi_analysis/main_window.py, package/PartSeg/_roi_analysis/measurement_widget.py, package/PartSeg/_roi_mask/main_window.py, package/PartSeg/common_gui/exception_hooks.py, package/PartSeg/common_gui/main_window.py, package/PartSeg/common_gui/multiple_file_widget.py, package/PartSeg/common_gui/waiting_dialog.py, package/PartSegCore/analysis/io_utils.py, package/PartSegCore/mask/io_functions.py, setup.cfg
also fix error reporting when load from the last files.
=> Fix python 3.9.7 bug 

package/PartSeg/_roi_analysis/advanced_window.py, package/PartSeg/_roi_analysis/main_window.py, package/PartSeg/_roi_analysis/measurement_widget.py, package/PartSeg/_roi_analysis/prepare_plan_widget.py, package/PartSeg/_roi_mask/main_window.py, package/PartSeg/_roi_mask/simple_measurements.py, package/PartSeg/common_backend/except_hook.py, package/PartSeg/common_gui/algorithms_description.py, package/PartSeg/common_gui/channel_control.py, package/PartSeg/common_gui/exception_hooks.py, package/PartSeg/common_gui/main_window.py, package/PartSeg/common_gui/universal_gui_part.py, package/PartSeg/custom_application/application.py, package/tests/test_PartSeg/test_channel_control.py, package/tests/test_PartSeg/test_common_gui.py, requirements/requirements_pyinstaller.in, setup.cfg
Change from `EnumComboBox` to `superqt.QEnumComboBox` and use `@ensure_main_thread` instead of `QMetaObject.invokeMethod`.
=> Use superqt

package/PartSeg/_roi_analysis/advanced_window.py, package/PartSeg/_roi_mask/main_window.py, package/PartSeg/common_gui/advanced_tabs.py, package/PartSeg/common_gui/algorithms_description.py, package/PartSeg/common_gui/main_window.py, package/PartSeg/common_gui/qt_console.py, package/PartSegCore/register.py, package/PartSegCore/segmentation/algorithm_base.py, package/PartSegCore/segmentation/restartable_segmentation_algorithms.py, package/PartSegCore/segmentation/segmentation_algorithm.py, package/PartSegCore/segmentation/watershed.py, package/PartSegImage/image.py, package/tests/test_PartSegCore/segmentation/test_segmentation_algorithm.py, package/tests/test_PartSegCore/test_segmentation.py, requirements/requirements_pyinstaller.txt
This PR contains refator of `segmentation_algorithm.py` and adding CellFromNucleusFlow method of whole cell segmentation. 
fix: console segfaulr
feat: enable reload in mask algorithm
=> feat: add CellFromNucleusFlow "Cell from nucleus flow" cell segmentation method 

package/PartSegCore/mask/io_functions.py, package/PartSegCore/roi_info.py, package/PartSegImage/image.py, package/tests/test_PartSegCore/test_io.py, tutorials/tutorial_neuron_types/Neuron_types_example.ipynb
Add option to keep data from original image around components. This may be helpful for denoising data with high background.
=> feat: When cutting components in PartSeg roi mask allow not masking outer data

build_utils/minimal-req.txt, package/PartSeg/_roi_analysis/main_window.py, package/PartSeg/_roi_mask/main_window.py, package/PartSeg/common_backend/base_settings.py, package/PartSeg/common_gui/advanced_tabs.py, package/PartSeg/common_gui/main_window.py, package/PartSeg/common_gui/napari_image_view.py, package/PartSeg/common_gui/napari_viewer_wrap.py, package/PartSeg/custom_application/application.py, setup.cfg, tox.ini
This PR adds theme selection in PartSeg settings and synchronizes it with napari settings.
=> feat: theme selection in GUI

package/PartSeg/_roi_analysis/advanced_window.py, package/PartSeg/_roi_analysis/batch_window.py, package/PartSeg/_roi_analysis/main_window.py, package/PartSeg/_roi_mask/main_window.py, package/PartSeg/common_backend/base_settings.py, package/PartSeg/common_gui/custom_load_dialog.py, package/PartSeg/common_gui/custom_save_dialog.py, package/PartSeg/common_gui/main_window.py, package/PartSeg/plugins/napari_widgets/roi_extraction_algorithms.py, package/tests/test_PartSeg/test_common_gui.py
In this PR two new classes `class PLoadDialog(CustomLoadDialog)` and `class PSaveDialog(CustomSaveDialog)` are added which support saving parameters in settings.
=> refactor: export common code for load/save dialog to one place

package/PartSeg/common_gui/multiple_file_widget.py, package/PartSeg/plugins/itk_snap_save/__init__.py, package/PartSeg/plugins/napari_widgets/roi_extraction_algorithms.py, package/PartSegCore/analysis/io_utils.py, package/PartSegImage/image.py, package/tests/test_PartSeg/test_napari_widgets.py, package/tests/test_PartSegImage/test_image.py
This PR adds annotation as properties of labels layer created with ROI Extraction widgets.
Also, add ROI extraction parameters to metadata.
=> feat: Add ROI annotations as properties to napari labels layer created by ROI Extraction widgets

package/PartSeg/common_backend/base_settings.py, package/PartSeg/common_gui/multiple_file_widget.py, package/tests/test_PartSeg/test_common_gui.py
Add last opened files to load recent files dialog of multiple files widget
=> Last files in multiple load dialog

package/PartSeg/_launcher/check_version.py, package/PartSeg/common_backend/load_backup.py, package/tests/test_PartSeg/test_check_release.py, package/tests/test_PartSeg/test_common_backend.py
This PR adds the "Ignore" button to the message about the new release which will suppress this message for 21 days.
=> feat: Allow ignore updates for 21 days

package/PartSeg/common_backend/load_backup.py, package/tests/test_PartSeg/test_common_backend.py
Fix bug from #453 
Add test for this
=> Fix try of removing `ignore.txt` if not exists

package/PartSeg/common_gui/main_window.py, package/PartSegCore/mask/io_functions.py, package/tests/test_PartSegCore/test_io.py
In this PR I add saving all components if no component is selected.
It also adds information about which from which folder comes currently opened file.
=> feat: Save all components if no components selected in mask segmentation

package/PartSegCore/analysis/measurement_base.py, package/tests/test_PartSegCore/test_measurements.py
=> Fix measurement prefix in bundled version.

package/PartSeg/common_gui/algorithms_description.py, package/PartSeg/plugins/napari_widgets/measurement_widget.py, package/PartSeg/plugins/napari_widgets/roi_extraction_algorithms.py, package/PartSeg/plugins/napari_widgets/search_label_widget.py, package/PartSegCore/analysis/measurement_calculation.py
Properties wrong assignment to components in the measurements
Fiz zoom to in 3D data for Search Label
=> fix: Bugs in napari plugins

package/PartSeg/_launcher/check_version.py, package/PartSeg/_roi_analysis/advanced_window.py, package/PartSeg/_roi_analysis/prepare_plan_widget.py, package/PartSeg/common_backend/base_settings.py, package/PartSeg/common_gui/about_dialog.py, package/PartSegCore/analysis/calculation_plan.py, package/PartSegCore/analysis/save_functions.py, package/PartSegCore/io_utils.py, package/PartSegCore/mask/io_functions.py
=> Force utf-8 usage for encoding files

changelog.md, requirements/requirements_pyinstaller.txt
Update changelog and some of requirements
=> Create 0.13.15 release

.sourcery.yaml, package/PartSeg/common_gui/collapse_checkbox.py, package/PartSegCore/analysis/batch_processing/batch_backend.py, package/PartSegCore/convex_fill.py, package/PartSegCore/io_utils.py
Fix deprecations reported in tests
=> Fix deprecations 

.github/workflows/test_prereleases.yml, .github/workflows/tests.yml, MANIFEST.in, package/PartSeg/_roi_analysis/main_window.py, package/PartSeg/_roi_analysis/prepare_plan_widget.py, package/PartSeg/_roi_mask/simple_measurements.py, package/PartSeg/common_backend/base_argparser.py, package/PartSeg/common_backend/base_settings.py, package/PartSeg/common_gui/algorithms_description.py, package/PartSeg/plugins/napari_widgets/roi_extraction_algorithms.py, package/PartSeg/plugins/napari_widgets/simple_measurement_widget.py, package/PartSegCore/analysis/calculation_plan.py, package/PartSegCore/analysis/load_functions.py, package/PartSegCore/analysis/measurement_base.py, package/PartSegCore/class_generator.py, package/PartSegCore/mask_create.py, package/PartSegCore/segmentation/restartable_segmentation_algorithms.py, package/tests/test_PartSeg/conftest.py, package/tests/test_PartSeg/test_common_backend.py, package/tests/test_PartSeg/test_napari_widgets.py, package/tests/test_PartSeg/test_settings.py, package/tests/test_PartSegCore/segmentation/test_algorithm_base.py, package/tests/test_PartSegCore/test_analysis_batch.py, package/tests/test_PartSegCore/test_mask_create.py, package/tests/test_PartSegCore/test_measurements.py, tox.ini
This PR contains sourcery updates and changes to call arguments by name, not by position. 
It is added to simplify #462
=> Apply non esentail parts of better serialization PR #462

package/PartSeg/_roi_analysis/prepare_plan_widget.py
=> feat: Add option to extract meaurement profile or roi extraction profile from batch plan

tox.ini
use 2.1.1.1 only for python 3.10
=> Limit simpleitk versions

package/PartSeg/_roi_analysis/image_view.py, package/tests/conftest.py, package/tests/test_PartSeg/roi_analysis/test_image_view.py
=> fix: Error when synchronization is loaded and new iloaded image has different dimensionality than currently loaded.

.github/workflows/test_napari_repo.yml, .github/workflows/test_prereleases.yml, .github/workflows/tests.yml, requirements/requirements_pyinstaller.in
=> Test if pyinstaller bundle work for --pre tests 

package/PartSeg/_roi_analysis/profile_export.py, package/tests/test_PartSeg/roi_analysis/test_profile_export.py, setup.cfg
=> fix: Fix profile export/import dialogs 

examples/convert_tiff_mask_to_projets.py, package/PartSeg/common_backend/__init__.py, package/PartSeg/common_backend/base_argparser.py, package/PartSeg/launcher_main.py, package/PartSegCore/segmentation/threshold.py, package/tests/test_PartSeg/test_launcher.py
speedup CLI show by delay imports
=> refactor: optimize CLI actions

package/PartSeg/_roi_mask/main_window.py, package/PartSegCore/mask/io_functions.py, package/tests/test_PartSegCore/test_io.py
=> fix: Fix bug when saving segmentation prameters in mask analysis

package/PartSeg/_roi_analysis/main_window.py, package/PartSeg/common_gui/algorithms_description.py, package/PartSeg/common_gui/napari_image_view.py, package/tests/test_PartSeg/conftest.py, package/tests/test_PartSeg/test_napari_image_view.py, setup.cfg
1. Block starting calculation when not all properties are set. 
2. Reset compare button to default state when load a new image. 
3. Fix double add of layers
=> fix: Fix multiple error related to loading new file in interactive mode

.sourcery.yaml, package/PartSeg/common_gui/algorithms_description.py, package/PartSeg/common_gui/universal_gui_part.py, package/PartSegCore/algorithm_describe_base.py, package/tests/test_PartSeg/test_common_gui.py, package/tests/test_PartSegCore/test_algorithm_describe_base.py
If algorithm properties contain a str field that will contain only `-` of length at least six, then it will be replaced with hline widget.
=> Add option to insert hline in algorithm description

.github/workflows/base_test_workflow.yml, .github/workflows/test_prereleases.yml, tox.ini
try to apply https://github.com/ymyzk/tox-gh-actions/issues/66
=> chore: Use `fail_on_no_env` feature from `tox-gh-actions` 

package/PartSeg/_roi_analysis/batch_window.py, package/PartSeg/common_backend/load_backup.py, package/PartSegCore/analysis/batch_processing/batch_backend.py, package/PartSegCore/analysis/calculation_plan.py, package/PartSegCore/analysis/measurement_calculation.py, package/tests/test_PartSeg/roi_analysis/test_batch.py, package/tests/test_PartSeg/test_common_backend.py, package/tests/test_PartSegCore/test_measurements.py
This PR adds an option to overwrite voxel size in batch processing. 
Also, add required tests and reactors in the code.
=> feat: Add voxel size measurement and allow to overwritte voxel size in batch

.github/workflows/tests.yml
* Using mambaforge (miniconda on conda-forge with preconfigured mamba)
* Adding `bash -el {0}` as the shell as per the [docs](https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell)
Comes from https://napari.zulipchat.com/#narrow/stream/212875-general/topic/conda.20problem.20in.20tests
=> Fix conda tests

build_utils/create_environment_yml.sh, build_utils/setup_cfg_to_yaml.sh, package/PartSeg/common_gui/advanced_tabs.py, package/PartSeg/common_gui/colormap_creator.py, package/PartSeg/common_gui/label_create.py, package/PartSegCore/io_utils.py, package/tests/test_PartSeg/test_colormap_create.py, package/tests/test_PartSeg/test_common_gui.py, package/tests/test_PartSeg/test_label_choose.py, setup.cfg
Use font awesome icons for edit/delete
=> feat: Add import and export operation for labels and colormaps

.github/workflows/base_test_workflow.yml, .github/workflows/test_napari_widgets.yml, .napari/DESCRIPTION.md, package/PartSeg/common_gui/algorithms_description.py, package/PartSeg/plugins/napari_widgets/__init__.py, package/PartSeg/plugins/napari_widgets/_settings.py, package/PartSeg/plugins/napari_widgets/algorithm_widgets.py, package/PartSeg/plugins/napari_widgets/roi_extraction_algorithms.py, package/PartSeg/plugins/napari_widgets/simple_measurement_widget.py, package/PartSegCore/algorithm_describe_base.py, package/PartSegCore/register.py, package/PartSegCore/segmentation/border_smoothing.py, package/PartSegCore/segmentation/restartable_segmentation_algorithms.py, package/PartSegCore/segmentation/segmentation_algorithm.py, package/PartSegCore/segmentation/watershed.py, package/tests/test_PartSeg/test_napari_widgets.py, package/tests/test_PartSegCore/test_analysis_batch.py, package/tests/test_PartSegCore/test_segmentation.py
This PR adds widgets that allow to interact with given algorithms from the group. This simplifies testing ad creating new workflows.
=> feat: Add napari widgets for all group of algoritms

.napari/DESCRIPTION.md, package/PartSeg/common_gui/algorithms_description.py, package/PartSeg/plugins/napari_widgets/algorithm_widgets.py, package/tests/test_PartSeg/test_napari_widgets.py
=> fix: Proper calculate bounds for watershed methods

.github/workflows/test_napari_repo.yml, .github/workflows/test_napari_widgets.yml, .github/workflows/test_prereleases.yml
=> fix: Bump OS versions for part of testing workflows. 

.azure-pipelines/tests.yaml, .github/workflows/tests.yml, tox.ini, toxfile.py
Use also a platform in json report name.
=> fix: Generate test report per platfom

.pre-commit-config.yaml
use black pre-compiled using mypyc
=> ci: use faster version of black
