package/PartSeg/_roi_analysis/partseg_settings.py, package/PartSeg/_roi_mask/stack_settings.py, package/PartSeg/common_backend/base_settings.py, package/PartSeg/common_gui/main_window.py, package/PartSeg/common_gui/napari_image_view.py, package/PartSegCore/analysis/io_utils.py, package/PartSegCore/analysis/load_functions.py, package/PartSegCore/io_utils.py, package/PartSegCore/mask/io_functions.py, package/PartSegCore/project_info.py, package/PartSegImage/image.py, package/tests/test_PartSeg/test_settings.py, package/tests/test_PartSegImage/test_image.py
This PR adds support of loading points (created for example in napari) to simplify verification of segmentation. 
Its only supports visualization and cutting points when select *Save components* in Mask ROI.
=> Add support of loading and visualize points from napari

changelog.md, package/PartSeg/_roi_analysis/partseg_settings.py, package/PartSeg/_roi_mask/stack_settings.py, package/PartSeg/common_backend/base_settings.py, package/PartSeg/common_gui/main_window.py, package/PartSeg/common_gui/napari_image_view.py, package/PartSegCore/analysis/io_utils.py, package/PartSegCore/analysis/load_functions.py, package/PartSegCore/io_utils.py, package/PartSegCore/mask/io_functions.py, package/PartSegCore/project_info.py, package/PartSegImage/image.py, package/tests/test_PartSeg/test_settings.py, package/tests/test_PartSegImage/test_image.py
This PR adds support of loading points (created for example in napari) to simplify verification of segmentation.
It only supports visualization and cutting points when select Save components in Mask ROI.
Fixed version of #197
=> Load and visualize points from napari

package/PartSegCore/segmentation/algorithm_base.py, package/tests/test_PartSegCore/segmentation/test_algorithm_base.py
set name for `AdditionalLayerDescription` is not set to the key of `SegmentationResult.additional_layers`
=> Update names of AdditionalLayerDescription if missed in SegmentationResult

package/PartSegCore/analysis/measurement_base.py
To reduce the chance to confuse measurement from a different plugins.
=> Add information to measurement about source plugin

MANIFEST.in, examples/call_simple_threshold.py, package/PartSegCore/roi_info.py, package/PartSegCore/segmentation/segmentation_algorithm.py, requirements/requirements_pyinstaller.txt, setup.cfg
In this PR there is a switch to cython backend for calculating the bounding box for ROI.
=> perf: Use faster calc bound function

package/PartSeg/_roi_analysis/image_view.py, package/PartSeg/_roi_mask/image_view.py, package/PartSeg/common_gui/custom_buttons.py, package/PartSeg/common_gui/napari_image_view.py, package/PartSeg/common_gui/qt_modal.py, package/tests/test_PartSeg/test_common_gui.py, package/tests/test_PartSeg/test_napari_image_view.py
This PR adds the possibility of a searching a single component by its number
There are two possible modes:
* **Highlight** - highlight selected component, view area is changed only fi component is not visible in the current field of view.,
* **Zoom in** - zoom to the component. Field of view is selected to be filed with the component. 
Currently, not all features work in 3D.
=> feat: Add modal dialog for search ROI components

package/PartSeg/common_gui/napari_image_view.py, package/tests/test_PartSeg/test_napari_image_view.py
To keep the interface more clear points toggle button will be hidden if there are no points.
=> fix: Hide points button if no points are loaded, hide Mask checkbox if no mask is set

package/PartSeg/_roi_analysis/image_view.py, package/PartSeg/common_gui/napari_image_view.py
This PR fixes the bug of not saving selected alternatives when setting new ROI from segmentation.
=> fix: ROI aternative reopresentation 

.github/workflows/test_prereleases.yml, .github/workflows/tests.yml
Because of problems described in https://github.com/GabrielBB/xvfb-action/issues/25 stop using GabrielBB/xvfb-action until the source of segfaults problem will be solved.
=> Not use GabrielBB/xvfb-action on non linux systems

package/PartSeg/common_gui/advanced_tabs.py, package/PartSeg/common_gui/custom_buttons.py, package/PartSeg/common_gui/napari_image_view.py, package/PartSeg/common_gui/universal_gui_part.py, package/tests/test_PartSeg/test_common_gui.py
This is the same as #538 but for PartSeg main GUI.
=> feat: Add controling of zoom factor of search ROI in main GUI

package/PartSegCore/analysis/load_functions.py
This PR also makes possible to load `*.obsep` file in napari reader plugin.
=> feat: Make `*.obsep" file possible to load in PartSeg Analysis

.github/workflows/test_napari_widgets.yml, package/PartSeg/_launcher/main_window.py, package/PartSeg/common_gui/algorithms_description.py, package/PartSeg/plugins/napari_widgets/__init__.py, package/PartSegCore/algorithm_describe_base.py, package/tests/test_PartSeg/test_main_windows.py, package/tests/test_PartSegCore/test_algorithm_describe_base.py, tox.ini
This PR introduces the option to launch PartSeg GUI from napari. This allows using the napari installer for non-pythonic users.
=> feat: Launch PartSeg GUI from napari

package/PartSeg/common_backend/segmentation_thread.py, package/PartSeg/common_gui/algorithms_description.py, package/tests/test_PartSeg/test_common_backend.py
This PR solves the bug of setting a new image to already running ROI Extraction algorithm. 
fix PARTSEG-K3
=> fix: Delay setting image if an algorithm is still running

.github/workflows/test_prereleases.yml, codecov.yml, package/tests/test_PartSeg/conftest.py, package/tests/test_PartSeg/test_check_release.py, package/tests/test_PartSeg/test_common_backend.py, package/tests/test_PartSeg/test_window_import.py, package/tests/test_PartSegCore/test_algorithm_describe_base.py, package/tests/test_PartSegCore/test_analysis_batch.py, package/tests/test_PartSegCore/test_io.py, package/tests/test_PartSegCore/test_measurements.py, package/tests/test_PartSegCore/test_mso.py, package/tests/test_PartSegCore/test_segmentation_proceses.py, package/tests/test_PartSegCore/test_utils.py, setup.cfg, tox.ini
Following https://nedbatchelder.com/blog/202008/you_should_include_your_tests_in_coverage.html
=> test: Add tests files to calcualate coverage

package/PartSeg/plugins/napari_widgets/search_label_widget.py
Hi everyone,
Thank you for creating this amazing piece of software!
I noticed that the maximum value for the search label widget is 999. Given that cell labels tend to be much larger than that would it make sense to increase the maximum? I couldn't find a way to make it unbounded but I figured a sensible max would be the largest value uint64 can encode.
What do you think?
=> Increase max value in SearchLabel widget

package/PartSeg/_roi_analysis/main_window.py, package/PartSeg/_roi_mask/main_window.py, package/PartSeg/common_gui/napari_image_view.py
Add an option to enable the toggle scale bar in the View menu.
=> feat: Add option to toggle scale bar

package/PartSeg/common_backend/base_argparser.py, package/PartSegCore/state_store.py
allow using `PARTSEG_SETTINGS_DIR` environment variable to set the default directory with PartSeg settings.
=> feat: Allow customize settings directory using the `PARTSEG_SETTINGS_DIR` environment variable

package/PartSeg/launcher_main.py
Allow to use `roi` instead of `roi_analysis` and mask instead of `mask_segmentation` when using CLI.
=> feat: Add `roi` and `mask` aliases when using CLI

package/PartSeg/common_gui/napari_image_view.py
This PR fixes a bug that the ROI layer is placed invalid if using interactive mode for work with PartSeg.
=> fix: ensure that "ROI" layer is in proper place for proper visualization

.github/workflows/test_prereleases.yml, .github/workflows/tests.yml, .pre-commit-config.yaml, setup.cfg, tox.ini
Add python 3.11 to list of supported python, but run test only on `main` and `develop` as there is a need to build `SimpleITK` from the source
=> chore: Add python 3.11 to list of supported versions

package/PartSeg/_roi_analysis/main_window.py, package/PartSeg/_roi_mask/main_window.py, package/PartSeg/common_gui/image_adjustment.py, package/PartSeg/common_gui/main_window.py, package/PartSegCore/image_transforming/__init__.py, package/PartSegCore/image_transforming/image_projection.py, package/PartSegCore/image_transforming/interpolate_image.py, package/PartSegCore/image_transforming/swap_time_stack.py, package/PartSegCore/image_transforming/transform_base.py, package/tests/test_PartSeg/roi_analysis/test_main_window.py, package/tests/test_PartSeg/roi_mask/test_main_window.py, package/tests/test_PartSegCore/test_image_adjustment.py, prospector.yml, pyproject.toml
In Image adjustment, add Image Projection (min, max, mean, sum) with ability to keep ROI and Mask.
=> feat: Add option to create projection alongside z-axis

package/PartSegCore/algorithm_describe_base.py, package/PartSegCore/mask/io_functions.py, package/tests/test_PartSegCore/test_algorithm_describe_base.py
This PR fixed bug that during the generation of the form, the hidden attribute was ignored.
=> bugfix: fix bug with generation of form for model with hidden field

package/PartSeg/_roi_analysis/main_window.py
In this PR, the check if all data required for save operations are present.
fix PARTSEG-RM
=> Protect from saving when mask or segmentation is absent

.github/workflows/base_test_workflow.yml, .gitignore, package/PartSegCore/analysis/batch_processing/batch_backend.py, package/PartSegCore/mask/io_functions.py, package/PartSegImage/image_reader.py, package/tests/test_PartSegCore/test_analysis_batch.py, tox.ini
This PR adds handling exceptions during the processing of mask project in roi batch to not drop all results when fails to process a single component. Instead of this, it will return error on list of results
=> feat: Do not abort processing whole mask segmentation project during exception on single component

launcher.spec, package/PartSeg/plugins/__init__.py, package/PartSegCore/plugins/__init__.py
replace `pkg_resources.iter_entry_points` with importlib.metadata.entry_points
=> refactor: Remove `pkg_resources` usage as it is deprecated

MANIFEST.in, azure-pipelines.yml, launcher.spec, package/PartSeg/launcher_main.py, package/PartSeg/napari.yaml, package/PartSeg/plugins/__init__.py, package/PartSeg/plugins/napari_widgets/__init__.py, package/PartSeg/plugins/napari_widgets/algorithm_widgets.py, package/PartSeg/plugins/napari_widgets/measurement_widget.py, package/PartSeg/plugins/napari_widgets/roi_extraction_algorithms.py, package/PartSeg/plugins/napari_widgets/simple_measurement_widget.py, package/PartSegCore/mask/io_functions.py, package/PartSegCore/napari_plugins/__init__.py, package/PartSegCore/napari_plugins/load_image.py, package/PartSegCore/napari_plugins/load_mask_project.py, package/PartSegCore/napari_plugins/load_masked_image.py, package/PartSegCore/napari_plugins/load_roi_project.py, package/PartSegCore/napari_plugins/save_mask_roi.py, package/PartSegCore/napari_plugins/save_tiff_layer.py, setup.cfg
pointed in https://github.com/napari/napari/issues/5738#issuecomment-1514985761
=> refactor: Convert napari plugin to npe2

.github/workflows/tests.yml
followup to #977
change from ubuntu 20.04 to 22.04
=> fix: Bump os version for main tests workflow.

launcher.spec, package/PartSeg/plugins/__init__.py
import plugin as `plugin_name` not `plugins.plugin_name`
fix PARTSEG-SV 
fix PARTSEG-ST
fix PARTSEG-SS
fix PARTSEG-SR
fix PARTSEG-SV
=> fix: importing plugins in bundle keeping proper module names 

.github/workflows/test_napari_repo.yml
Bump system to Ubuntu 22.04 for compatibility with `PyQt6==6.5.1`
Change to `aganders3/headless-gui` 
closes #984
=> fix: Fix napari repo workflow

package/PartSegCore/algorithm_describe_base.py, package/PartSegCore/segmentation/restartable_segmentation_algorithms.py, package/PartSegCore/segmentation/threshold.py, package/tests/conftest.py, package/tests/test_PartSegCore/test_io.py, package/tests/test_PartSegCore/test_segmentation.py, package/tests/test_data/range_profile.json
This Pr fix information on which threshold is lower and upper in the Range Threshold algorithm.
It removes Multiple Otsu and Maximum distance cores from the list of available methods as they will not be adequately used in this context.
=> fix: Fix range threshold selection of algorithms
